import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar';
import Featured from '../components/Featured';
import HotProducts from '../components/HotProducts';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fashionbulous</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </Head>

      <NavBar />

      <main>
        <Hero />
        <Featured />
        <HotProducts />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

/**
 *! Red (!)
 *? Blue (?)
 **Green (*)
 *^Yellow (^)
 *&Pink (&)
  Purple (~)
  Mustard (todo)
  Grey (//)
 */
